### ISSUE TITLE
Particles list is outdated

### ISSUE THREAD

**Issue by Evtema3** [ErrorCraft/FunctionAnalyser#2]
The analyzer does not recognize the following valid particle IDs as of Java Edition 1.19 (list compiled from https://github.com/misode/mcmeta/blob/registries/particle_type/data.json):
- `block_marker`
- `electric_spark`
- `falling_spore_blossom`
- `scrape`
- `sculk_soul`
- `spore_blossom_air`
- `wax_off`
- `wax_on`

It also currently recognizes `barrier`, which has been removed since 21w42a, and `sculk_smoke`, which does not exist (presumably a typo for `sculk_soul`).

**Comment by ErrorCraft** [comment]
The missing particles were added and the invalid ones removed. I also moved some of them so they're alphabetical now.
